AllCops:
  TargetRubyVersion: 2.5
  Include:
    - '**/*.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/LineLength:
  Max: 90
Metrics/MethodLength:
  Max: 12
